### ISSUE TITLE
Unable to open the DropPlan after changing "Highlight" options to value "Parent"

### ISSUE THREAD

**Issue by cscheidsteff** [yanivsegev/VSTS-DropPlan#128]
After changing the value of the "Highlight"-Dropdown to "Parent"
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/105804990/abe4d00e-a934-42d1-86dc-7d044ca16760)
the DropPlan can no longer be opened for the sprint being set at that time. The error message varies depending on the browser

Chrome:
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/105804990/c2494a15-f385-4399-b962-f7b0b5612916)

Firefox:
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/105804990/b013fb72-a999-4317-b082-c755596b8af3)

**Comment by sgtwilko** [comment]
@cscheidsteff 
I think this is the same issue as #129 
Can you confirm if this only happens when you change the highlight, or in general using sprint plan?

**Comment by cscheidsteff** [comment]
> @cscheidsteff I think this is the same issue as #129 Can you confirm if this only happens when you change the highlight, or in general using sprint plan?

@sgtwilko we will check this

**Comment by yanivsegev** [comment]
@cscheidsteff ,
I believe this issue is related to the different time zones in Azure DevOps.
In version 2.2.3, I've added a new experimental time management feature - you can enable it in the Project Settings -> Drop Plan Settings -> "Use new time management".

Can you please check this with the new settings and see if it gets better?

**Comment by cscheidsteff** [comment]
@yanivsegev yes, this solved the problem. Thx!
