### ISSUE TITLE
Drop Plan is not showing 

### ISSUE THREAD

**Issue by JiBeit** [yanivsegev/VSTS-DropPlan#129]
![Uploading MicrosoftTeams-image.png…]()
After clicking the drop plan its showing shite screen only 
![Uploading MicrosoftTeams-image.png…]()

**Comment by sgtwilko** [comment]
@JiBeit your images aren't showing, please can you upload again.
Thanks

**Comment by JiBeit** [comment]
![image (1)](https://github.com/yanivsegev/VSTS-DropPlan/assets/145749388/397986f8-4395-452c-8264-a108796b19e2)

**Comment by rovelgoenne** [comment]
same problem here:
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/37324522/d9d20a9d-d9ba-4e6a-a49a-a59c3a3012b1)

**Comment by yanivsegev** [comment]
@rovelgoenne , @JiBeit , @sgtwilko 
I believe this issue is related to the different time zones in Azure DevOps.
In version 2.2.3, I've added a new experimental time management feature - you can enable it in the Project Settings -> Drop Plan Settings -> "Use new time management".

Can you please check this with the new settings and see if it gets better?

**Comment by JiBeit** [comment]
@yanivsegev Thanks its solved the issue

**Comment by cscheidsteff** [comment]
> @yanivsegev Thanks its solved the issue

with us as well, thx
