### ISSUE TITLE
Drop Plan showing Multiple Sundays and not showing correctly. 

### ISSUE THREAD

**Issue by KennedyNNNN** [yanivsegev/VSTS-DropPlan#130]
Days off are just Saturdays and Sundays. But the image below is showing differently, and it is affecting planning. 

![Drop Plan issue](https://github.com/yanivsegev/VSTS-DropPlan/assets/162513767/fc0d850a-ffe6-45cf-8ee3-aa1c79abfb3f)

**Comment by yanivsegev** [comment]
@KennedyNNNN ,
I believe this issue is related to the different time zones in Azure DevOps.
In version 2.2.3, I've added a new experimental time management feature - you can enable it in the Project Settings -> Drop Plan Settings -> "Use new time management".

Can you please check this with the new settings and see if it gets better?
