### ISSUE TITLE
Azure DevOps Boards — Drop Plan not loading

### ISSUE THREAD

**Issue by sejal-ss** [yanivsegev/VSTS-DropPlan#131]
Hi,

I am attempting to access my organization's Board: Drop Plan to view my tasks, but the browser page is not loading.

Please refer to the attached screenshot of the error and console logs.

<img width="960" alt="1" src="https://github.com/yanivsegev/VSTS-DropPlan/assets/162682039/6817f417-c7b0-43a0-99fe-96dd0a38767d">

[prodngahr.visualstudio.com-1709884349168.log](https://github.com/yanivsegev/VSTS-DropPlan/files/14535380/prodngahr.visualstudio.com-1709884349168.log)

**Comment by yanivsegev** [comment]
@sejal-ss 

I believe this issue is related to the different time zones in Azure DevOps.
In version 2.2.3, I've added a new experimental time management feature - you can enable it in the Project Settings -> Drop Plan Settings -> "Use new time management".

Can you please check this with the new settings and see if it gets better?

**Comment by sejal-ss** [comment]
@yanivsegev Thank you. Enabling “Use new time management” setting resolved my issue.

<img width="699" alt="2" src="https://github.com/yanivsegev/VSTS-DropPlan/assets/162682039/e80659ae-8f92-4c78-a105-b66ca0316f2d">
